services:
  - type: web
    name: sena-voting-backend
    env: node
    plan: starter
    buildCommand: npm run render-build
    startCommand: npm run render-start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /opt/render/.cache/puppeteer/chrome/linux-139.0.7258.68/chrome-linux64/chrome
    disk:
      name: puppeteer-cache
      mountPath: /opt/render/.cache/puppeteer
      sizeGB: 1